services:
  webapp:
    image: php:apache
    container_name: webapp
    depends_on:
      - student_api
    ports:
        - "8080:80"
    volumes:
        - ./website/:/var/www/html
    environment:
        - USERNAME=toto
        - PASSWORD=python
    networks:
      - student_network

  student_api:
    image: student-api:v1.0
    container_name: student_api
    # ports:
    #  - 5000
    volumes:
      - './simple_api/student_age.json:/data/student_age.json'
    networks:
      - student_network

networks:
  student_network:
    name: student_network
    driver: bridge
